feat: support omise payment gateway
quintype/quintype-node-components pull request #186
Opened 2021-06-17 04:34 UTC by ReenaSingh07

Fixes https://github.com/quintype/madrid/issues/3684

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Tested the one time and recurring subscription plans with omise payment gateway

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-06-17 06:04 UTC, ReenaSingh07 commented
due to business requirement, this feature has to be taken to production soon, will add the unit test case at later point of time

2021-06-17 06:09 UTC, EnKrypt commented
Deleted comment by mistake

2021-06-17 06:19 UTC, ReenaSingh07 commented
due to business requirements, we are taking this feature without unit tests. Will add the unit test in the below-mentioned ticket https://github.com/quintype/madrid/issues/3757

2021-06-17 06:23 UTC, Jeevan-Kishore requested changes

2021-06-17 06:23 UTC, Jeevan-Kishore commented on src/components/access-type.js
> +    return omise
```suggestion
      if(!omise){
          return Promise.reject({ message: "Payment option is loading..." });
          }
```

2021-06-21 04:22 UTC, Jeevan-Kishore approved these changes

2021-06-21 04:49 UTC, EnKrypt requested changes

2021-06-21 04:49 UTC, EnKrypt commented on src/components/access-type.spec.js
> +                return { proceed: (j) => j };
Please change to more descriptive variable names instead of `x`, `i`, and `j` in all instances

2021-06-21 04:49 UTC, EnKrypt commented on src/components/access-type.spec.js
> +  it("Failed omise payment ", () => {
Can mention when it is expected to fail in the test description

2021-06-21 09:30 UTC, EnKrypt approved these changes

2021-06-21 09:37 UTC, EnKrypt requested changes

2021-06-21 09:37 UTC, EnKrypt commented on src/components/access-type.spec.js
> +    });
Can't await like this, we need to check the result of the promise instead of reaching into `.reject`

2021-06-21 09:55 UTC, EnKrypt approved these changes

2021-06-21 10:01 UTC, Athira001 approved these changes

2021-06-22 12:01 UTC, merged